#!/bin/sh
set -ex

BATCH=""
if [ -n "$1" ]
then
    if [ "$1" = "--batch" ]
    then
        BATCH="yes"
    else
        echo "Unknown parameter $1" 1>&2
        exit 1
    fi
fi

if [ "`hostname`" != "merlock" ]
then
    if nc merlock.microcomaustralia.com.au ssh < /dev/null > /dev/null
    then
        host=merlock.microcomaustralia.com.au
    else
        host=merlock.pri
    fi

    UNISON_ARGS="/home/brian ssh://$host//home/brian"
    UNISON_ARGS="$UNISON_ARGS -path tree -path encrypted/home -path encrypted/vpac -path encrypted/backdoors"

    if [ -n "$BATCH" ]
    then
        unison -batch $UNISON_ARGS
    else
        unison-gtk $UNISON_ARGS
    fi
fi

exit 0
