#!/bin/sh
set -e
if [ "$1" = "--rebuild" ]
then
    OPT="--rebuild"
    shift
else
    OPT="--refresh"
fi

doit() {
    local i="$1"
    if ! [ -e "$i.umask" ]
    then
        echo "Cannot find $i.umask" 1>&2
        exit 1
    fi
    if ! [ -e "$i.setup" ]
    then
        echo "Cannot find $i.setup" 1>&2
        exit 1
    fi

    umask `cat "$i.umask"`
    ikiwiki --setup $i.setup --verbose "$OPT"
}

if [ -z "$*" ]
then
    while [ "$PWD" != "/" ]
    do
        name="../$(basename "$PWD")"
        umaskfile="../$(basename "$PWD").umask"
        setupfile="../$(basename "$PWD").setup"
        if [ -f "$umaskfile" -a -f "$setupfile" ]
        then
            doit "$name"
            exit 0
        fi
        cd ..
    done
    echo "Not in a project directory" >&2
    exit 1
else
    for i in "$@"
    do
        doit "$i"
    done
fi
