#!/usr/bin/python
import os
import sys
import time
import signal

def check_status(status):
    if status != 0:
        print "Child returned %d"%status
        sys.stdin.readline()
    exit(status)

def handler(signum, frame):
    pid,status = os.waitpid(child, 0)
    check_status(status)

signal.signal(signal.SIGCHLD, handler)
child=os.fork()
if child==0:
    os.execvp(sys.argv[1],sys.argv[1:])
    sys.exit(1)
else:
    time.sleep(5)
