#!/usr/bin/python
import os
import sys
import subprocess

try:
    status = subprocess.check_call(sys.argv[1:])
    if status != 0:
        print "Child returned %d"%status
        sys.stdin.readline()
    exit(status)
except Exception, e:
    print e
    sys.stdin.readline()
    exit(1)
