#!/bin/sh -ex
dns="$(cat /etc/resolv.conf | sed -n 's/nameserver //p' | head -1)"
$HOME/tree/sshuttle.tproxy/iproutes

if [ "$1" = "--ipv6" ]
then
    shift
    exec "$HOME/tree/bin/sshuttle" -r webby.microcomaustralia.com.au 192.168.0.0/16 59.167.180.192/29 2001:44b8:4112:8a00::/56 --exclude 2001:44b8:4112:8a03::3 -vv --dns "$@"
else
    exec "$HOME/tree/bin/sshuttle" -r webby.microcomaustralia.com.au 192.168.0.0/16 59.167.180.192/29 -vv --dns "$@"
fi
