#!/bin/sh
set -ex

if [ -z "$TMP" ]
then
    TMP=/tmp
fi

DST="$TMP/sshuttle"

rm -rf "$DST"
cp -a "$HOME/tree/sshuttle.tproxy" "$DST"
export PYTHONPATH="/tmp/sshuttle/PyXAPI-0.1/build/lib.linux-$(arch)-2.7"
"$DST/sshuttle" "$@"
