#!/bin/sh -ex
dns="$(cat /etc/resolv.conf | sed -n 's/nameserver //p' | head -1)"

if [ "$1" = "--ipv6" ]
then
    shift
    exec "$HOME/tree/bin/sshuttle" -r webby.microcomaustralia.com.au 192.168.0.0/16 59.167.180.192/29 2001:44b8:758e:21e0::0/60 --exclude 2001:44b8:758e:21e3::3 -vv --dns "$@"
else
    exec "$HOME/tree/bin/sshuttle" -r webby.microcomaustralia.com.au 192.168.0.0/16 59.167.180.192/29 -vv --dns "$@"
fi
